# Generated by Django 4.2.5 on 2025-11-17 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sitio1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_actividad', models.CharField(choices=[('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('editar_perfil', 'Actualización de perfil'), ('cambio_password', 'Cambio de contraseña'), ('crear_producto', 'Creación de producto'), ('editar_producto', 'Edición de producto'), ('eliminar_producto', 'Eliminación de producto'), ('crear_venta', 'Nueva venta'), ('crear_orden', 'Nueva orden de compra')], max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('detalles', models.JSONField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Actividad de Usuario',
                'verbose_name_plural': 'Actividades de Usuarios',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
