# Generated by Django 4.2.5 on 2025-11-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio1', '0002_actividadusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadusuario',
            name='tipo_actividad',
            field=models.CharField(choices=[('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('editar_perfil', 'Actualización de perfil'), ('cambio_password', 'Cambio de contraseña'), ('crear_producto', 'Creación de producto'), ('editar_producto', 'Edición de producto'), ('eliminar_producto', 'Eliminación de producto'), ('crear_venta', 'Nueva venta')], max_length=50),
        ),
    ]
