# Generated by Django 4.2.5 on 2025-11-17 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sitio1', '0003_alter_actividadusuario_tipo_actividad'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCompraIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(db_index=True, max_length=50, unique=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('revision', 'En Revisión'), ('aprobada', 'Aprobada'), ('enviada', 'Enviada'), ('recibida_parcial', 'Recibida Parcial'), ('recibida_completa', 'Recibida Completa'), ('cancelada', 'Cancelada')], default='borrador', max_length=20)),
                ('observaciones_ia', models.TextField(blank=True, help_text='Análisis automático de la IA')),
                ('observaciones_usuario', models.TextField(blank=True, help_text='Notas del usuario')),
                ('total_productos', models.IntegerField(default=0)),
                ('total_unidades', models.IntegerField(default=0)),
                ('total_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('email_enviado', models.BooleanField(default=False)),
                ('email_enviado_fecha', models.DateTimeField(blank=True, null=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden de Compra IA',
                'verbose_name_plural': 'Órdenes de Compra IA',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='LogOrdenCompraIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(max_length=50)),
                ('detalle', models.TextField(blank=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='sitio1.ordencompraia')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log Orden Compra',
                'verbose_name_plural': 'Logs Órdenes Compra',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrdenCompraIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_actual', models.IntegerField(help_text='Stock al momento de generar orden')),
                ('demanda_estimada_14d', models.IntegerField(help_text='Demanda estimada 14 días')),
                ('dias_hasta_agotamiento', models.IntegerField(help_text='Días estimados hasta agotamiento')),
                ('nivel_criticidad', models.CharField(help_text='crítico, alto, medio, bajo', max_length=20)),
                ('cantidad_sugerida_ia', models.IntegerField(help_text='Cantidad sugerida por IA')),
                ('cantidad_solicitada', models.IntegerField(help_text='Cantidad final solicitada (editable)')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad_recibida', models.IntegerField(default=0)),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True)),
                ('observaciones_recepcion', models.TextField(blank=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sitio1.ordencompraia')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitio1.productos')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sitio1.proveedor')),
            ],
            options={
                'verbose_name': 'Item Orden Compra',
                'verbose_name_plural': 'Items Orden Compra',
                'ordering': ['nivel_criticidad', '-demanda_estimada_14d'],
            },
        ),
    ]
