# Generated by Django 4.2.5 on 2025-11-19 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sitio1', '0004_ordencompraia_logordencompraia_itemordencompraia'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField(help_text='Razón del ajuste de inventario')),
                ('productos_revisados', models.IntegerField(default=0)),
                ('productos_con_diferencias', models.IntegerField(default=0)),
                ('finalizado', models.BooleanField(default=False)),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sitio1.ubicacion')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ajuste de Inventario',
                'verbose_name_plural': 'Ajustes de Inventario',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='DetalleAjusteInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_sistema', models.IntegerField(help_text='Stock en el sistema antes del ajuste')),
                ('stock_fisico', models.IntegerField(help_text='Stock contado físicamente')),
                ('diferencia', models.IntegerField(help_text='Diferencia (físico - sistema)')),
                ('ubicacion_especifica', models.CharField(blank=True, help_text='Ej: A1-B2', max_length=100, null=True)),
                ('ajuste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='sitio1.ajusteinventario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitio1.productos')),
            ],
            options={
                'verbose_name': 'Detalle Ajuste Inventario',
                'verbose_name_plural': 'Detalles Ajuste Inventario',
                'ordering': ['producto__nombre'],
            },
        ),
    ]
