# Generated by Django 4.2.5 on 2025-11-19 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sitio1', '0005_ajusteinventario_detalleajusteinventario'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabla', models.CharField(choices=[('productos', 'Productos'), ('categorias', 'Categorías'), ('usuarios', 'Usuarios'), ('roles', 'Roles'), ('ajustes', 'Ajustes de Inventario'), ('proveedores', 'Proveedores'), ('ubicaciones', 'Ubicaciones'), ('ventas', 'Ventas')], max_length=50)),
                ('tipo_accion', models.CharField(choices=[('create', 'Creación'), ('update', 'Modificación'), ('delete', 'Eliminación'), ('view', 'Visualización')], max_length=10)),
                ('id_registro', models.IntegerField(help_text='ID del registro modificado')),
                ('descripcion', models.TextField(help_text='Descripción de la acción')),
                ('valores_anterior', models.JSONField(blank=True, help_text='Valores antes del cambio', null=True)),
                ('valores_nuevo', models.JSONField(blank=True, help_text='Valores después del cambio', null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Auditoría',
                'verbose_name_plural': 'Logs de Auditoría',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['usuario', '-fecha_hora'], name='sitio1_loga_usuario_6cc827_idx'), models.Index(fields=['tabla', '-fecha_hora'], name='sitio1_loga_tabla_4af451_idx'), models.Index(fields=['tipo_accion', '-fecha_hora'], name='sitio1_loga_tipo_ac_f870de_idx')],
            },
        ),
    ]
