# Generated by Django 4.2.5 on 2025-11-19 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sitio1', '0006_logauditoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleajusteinventario',
            options={},
        ),
        migrations.AlterField(
            model_name='ajusteinventario',
            name='motivo',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ajusteinventario',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='detalleajusteinventario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sitio1.productos'),
        ),
        migrations.AlterField(
            model_name='detalleajusteinventario',
            name='stock_fisico',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='detalleajusteinventario',
            name='stock_sistema',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='detalleajusteinventario',
            name='ubicacion_especifica',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='detalleajusteinventario',
            unique_together={('ajuste', 'producto')},
        ),
        migrations.RemoveField(
            model_name='detalleajusteinventario',
            name='diferencia',
        ),
    ]
