# Generated by Django 4.2.5 on 2025-12-05 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitio1', '0007_alter_detalleajusteinventario_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleajusteinventario',
            options={'ordering': ['producto__nombre'], 'verbose_name': 'Detalle Ajuste Inventario', 'verbose_name_plural': 'Detalles Ajuste Inventario'},
        ),
        migrations.AddField(
            model_name='detalleajusteinventario',
            name='diferencia',
            field=models.IntegerField(default=0, help_text='Diferencia (físico - sistema)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ajusteinventario',
            name='motivo',
            field=models.TextField(help_text='Razón del ajuste de inventario'),
        ),
        migrations.AlterField(
            model_name='detalleajusteinventario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitio1.productos'),
        ),
        migrations.AlterField(
            model_name='detalleajusteinventario',
            name='stock_fisico',
            field=models.IntegerField(help_text='Stock contado físicamente'),
        ),
        migrations.AlterField(
            model_name='detalleajusteinventario',
            name='stock_sistema',
            field=models.IntegerField(help_text='Stock en el sistema antes del ajuste'),
        ),
        migrations.AlterField(
            model_name='detalleajusteinventario',
            name='ubicacion_especifica',
            field=models.CharField(blank=True, help_text='Ej: A1-B2', max_length=100, null=True),
        ),
    ]
